routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
include 'route-admin.php';

Route::group(['namespace' => 'Auth', 'prefix' => 'account'], function() {
	Route::get('login', 'LoginController@getLogin')->name('auth.product.login');
	Route::post('login', 'LoginController@postLogin')->name('auth.product.login');

	Route::get('register', 'RegisterController@index')->name('auth.product.register');
});

Route::group(['prefix' => ''], function() {
	Route::get('/', 'HomeController@index');
	Route::get('/cart', 'CartController@index')->name('layouts.product.cart');
	Route::get('/{cateSlug}/{slug}', 'ProductDetailController@index')->name('layouts.product.detail');
});

app/Models/Attribute.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Attribute extends Model
{
    protected $table = 'attributes';
    protected $guarded = [];

    /**
     *
     *  relationship 1-n (1 Attribute Group - n Attribute)
     *  
     *
     */
    public function attribute_group() {
    	return $this->belongsTo('App\Models\AttributeGroup', 'atb_group_id');
    }

    public function values() {
        return $this->hasMany('App\Models\AttributeValue', 'atb_id');
    }

    public function getDeleteId($values = []) {
        return $this->values()
                    ->pluck('id')
                    ->diff($values);
    }
}

app/Http/Controllers/Admin/AdminSliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\AdminRequestSlider;
use App\Models\Slider;
use Carbon\Carbon;
use Image;
use DataTables;

class AdminSliderController extends Controller
{
    public function index() {
    	return view('admin.slider.index');
    }

    public function getList() {
    	$slide = Slider::latest()->get();
    	return DataTables::of($slide)
    	                 ->addIndexColumn()
    	                 ->editColumn('image', function($data) {
    	                 	return '<img class="img-fluid" width="200px;" src="'.pare_url_file($data->image, 'slider').'" alt="">';
    	                 })
    	                 ->editColumn('status', function($data) {
		                    $hide = '<a href="'.route('admin.slider.active', $data->id).'" class="badge badge-secondary">Hide</a>';
		                    if($data->status === 1)
		                        $hide = '<a href="'.route('admin.slider.active', $data->id).'" class="badge badge-success">Show</a>';
		                    return $hide;

			             })
    	                 ->addColumn('action', function($data){
		                    return
		                    '<a href="'.route('admin.slider.update', $data->id).'" class="btn btn-xs btn-info"><i class="fa fa-pencil"> Edit</i></a>
		                     <a href="#" class="btn btn-danger btn-xs ml-2"><i class="fa fa-trash"> Delete</i></a>';
		                })
    	                ->rawColumns(['action', 'image', 'status'])
                        ->make(true);
    }

    public function create() {
    	return view('admin.slider.create');
    }

    public function edit($id) {
    	$slide = Slider::findOrFail($id);

    	return view('admin.slider.update', compact('slide'));
    }

    public function store(AdminRequestSlider $request) {
    	$data = $request->all();
    	if($request->isMethod('post')) {
    		$slide = new Slider;

    		$slide->title      = $data['txt_title'];
    		$slide->link       = $data['txt_link'];
    		$slide->status     = $data['txt_status'];
    		$slide->order      = $data['txt_order'];
    		$slide->created_at = Carbon::now();

    		$file = $request->file('txt_image');
    		if(!empty($file)) {
    			$image = upload_image('txt_image', 'slider');
    			if($image['code'] === 1) {    				
    				$pathImage = $image['path_folder'].$image['name'];
                    Image::make($file)->resize(800,390)->save($pathImage);

                    $slide->image = $image['name'];
    			}
    		}

    		$slide->save();
    		return redirect()->route('admin.slider.index')->with('success', 'Slider has been added successfully!');
    	}
    	return redirect()->back();
    }

    public function update(AdminRequestSlider $request, $id) {
    	$slide = Slider::findOrFail($id);

    	if($request->isMethod('post')) {
    		$data = $request->all();

    		$slide->title      = $data['txt_title'];
    		$slide->link       = $data['txt_link'];
    		$slide->status     = $data['txt_status'];
    		$slide->order      = $data['txt_order'];
    		$slide->updated_at = Carbon::now();

    		$file = $request->file('txt_image');
    		if(!empty($file)) {
    			$image = upload_image('txt_image', 'slider');
    			if($image['code'] === 1) {    				
    				$pathImage = $image['path_folder'].$image['name'];
                    Image::make($file)->resize(800,390)->save($pathImage);

                    $slide->image = $image['name'];
    			}
    		}

    		$slide->save();
    		return redirect()->route('admin.slider.index')->with('success', 'Slider has been updated successfully!');
    	}
    }

    public function active($id) {
    	$slide = Slider::find($id);

    	$slide->status = !$slide->status;

    	$slide->save();
    	return redirect()->back();
    }

    public function deleteSliderImage($id = null) {
    	$slide = Slider::findOrFail($id);

    	$imgPath = public_path().'/images/slider/'.date('Y/').$slide->image;

    	if(file_exists($imgPath)) {
    		unlink($imgPath);
    	}

    	$slide->update(['image' => '']);
    	return redirect()->back()->with('success', 'Slider image has been deleted successfully!');
    }
}

resources/views/admin/attribute/attribute-specification/create.blade.php
@extends('admin.layout.master-admin')
@section('content')
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark">Attribute</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="#">Home</a></li>
					<li class="breadcrumb-item"><a href="#">Attribute</a></li>
					<li class="breadcrumb-item active">New</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>
<!-- Main content -->
<section class="content">
	<!-- Default card -->	
	<div class="row">
		<div class="col-12">
			<div class="card card-primary">
				<div class="card-header">
					<h3 class="card-title">Create Attribute</h3>
				</div>   
				<div class="card-body">					
					<div class="row">
						<div class="col-3">
							<h4>Attribute Information</h4>
							<div class="nav flex-column nav-tabs fix-tab" id="vert-tabs-tab" role="tablist" aria-orientation="vertical">
								<a class="nav-link active" id="vert-tabs-general-tab" data-toggle="pill" href="#vert-tabs-general" role="tab" aria-controls="vert-tabs-general" aria-selected="true">General</a>
								<a class="nav-link" id="vert-tabs-value-tab" data-toggle="pill" href="#vert-tabs-value" role="tab" aria-controls="vert-tabs-value" aria-selected="false">Values</a>
							</div>
						</div>
						<div class="col-9">
							<div class="tab-content" id="vert-tabs-tabContent">
								<div class="tab-pane tab-fix text-left fade show active" id="vert-tabs-general" role="tabpanel" aria-labelledby="vert-tabs-general-tab">
									<form action="" method="POST" class="form-horizontal">
										@csrf
										<h4>General</h4>
										<div class="form-group">
											<div class="row">
												<label for="attribute-group" class="col-md-3">Attribute Group <span class="text-danger">*</span></label>
												<div class="col-md-6">
													<select class="form-control {{ $errors->first('txt_attributeGroup') ? 'is-invalid' : ''}}" name="txt_attributeGroup">
														<option disabled selected>--Select choose option--</option>
														@foreach($categories as $cate)
															 <optgroup label="{{ $cate->c_name}}">
															 	@foreach($attributeGroup as $attr)
															 		@if($cate->att_category_id == $attr->att_category_id)
															 			<option value="{{$attr->id}}">
															 				{{$attr->att_name}}
															 			</option>
															 		@endif
															 	@endforeach
															 </optgroup>
														@endforeach
													</select>
													@if ($errors->first('txt_attributeGroup'))
						            					<p class="text-danger">{{ $errors->first('txt_attributeGroup') }}</p>
						            				@endif
												</div>
											</div>
										</div>
										<div class="form-group">
											<div class="row">
												<label for="attribute-name" class="col-md-3">Name <span class="text-danger">*</span></label>
												<div class="col-md-6">
													<input type="text" name="txt_attributeName" class="form-control {{ $errors->first('txt_attributeName') ? 'is-invalid' : '' }}" placeholder="Name" autocomplete="off">
													@if ($errors->first('txt_attributeName'))
						            					<p class="text-danger">{{ $errors->first('txt_attributeName') }}</p>
						            				@endif
												</div>
											</div>
										</div>
										<div class="form-group">
											<div class="row">
												<label for="attribute-filter" class="col-md-3">Filterable</label>
												<div class="col-md-6">
													<div class="custom-control custom-checkbox">
							                          <input class="custom-control-input" type="checkbox" id="customCheckbox1" value="option1">
							                          <label for="customCheckbox1" class="custom-control-label">Use this attribute for filtering products</label>
							                        </div>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-6 offset-md-3">
												<button type="submit" class="btn btn-success">Save <i class="fa fa-save"></i></button>
											</div>
										</div>
									</form>
								</div>
								<div class="tab-pane tab-fix fade" id="vert-tabs-value" role="tabpanel" aria-labelledby="vert-tabs-value-tab">
									<form action="" method="POST" class="form-horizontal">
										@csrf
										<h4>Values</h4>
										<div class="table-responsive">
											<table class="table-attribute border">
												<thead class="border-bottom">
													<tr>
														<th></th>
														<th>Value</th>
														<th></th>
													</tr>
												</thead>
												<tbody>
													<tr>
														<td class="drag-attribute"><i class="fas fa-bars"></i></td>
														<td class="px-2"><input type="text" autocomplete="off" class="form-control" name="txtAttributeValue[]" required></td>
														<td class="trash-attribute"><button class="btn btn-default btn-remove" title="Delete Value"><i class="fa fa-trash"></i></button></td>
													</tr>
												</tbody>
											</table>
										</div>
										<div class="attribute-btn d-flex flex-column align-items-start">
											<button class="btn btn-default my-3">Add New Value</button>
											<button class="btn btn-primary">Save</button>
										</div>
									</form> 
								</div>
							</div>
						</div>
					</div>
				</div>         
			</div>
			<!-- /.box -->
		</div>
	</div>
</section><!-- /.content -->

@endsection

resources/views/admin/attribute/attribute-specification/index.blade.php
@extends('admin.layout.master-admin')
@section('content')
<div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">Attribute</h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="#">Attribute</a></li>
            <li class="breadcrumb-item active">List</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- Main content -->
<section class="content">
	<!-- Default card -->
	<div class="row">
		<div class="col-12">
			<div class="card">
	            <div class="card-header">
	              <h3 class="card-title">List Attributes</h3>
	              <div class="card-tools">
	              	<a href="{{ route('admin.attribute.create') }}" class="btn btn-primary"><i class="fa fa-plus"></i> Create Attribute</a>
	              </div>
	            </div>
            	<!-- /.card-header -->
	            <div class="card-body">
	            	@include('admin.flash-message.flash-message')	            	
	            	
		            <table id="attribute" class="table table-bordered table-striped">
		                <thead>
			                <tr>
			                	<th>#</th>
			                	<th>Attribte group</th>
			                  	<th>Name</th>			                  	
			                  	<th>Filterable</th>
			                  	<th>Action</th>
			                </tr>
		                </thead>
		                               
		            </table>
		            
	            </div>
            	<!-- /.box-body -->
          </div>
		<!-- /.box -->
		</div>
	</div>
</section><!-- /.content -->
		
@endsection

@section('scripts')
	<script>
		$(document).ready(function() {
			$('#attribute').DataTable({
				processing: true,
	        	serverSide: true,
	        	responsive: true,
	        	ajax: '{{ route('admin.attribute.list') }}',
	        	columns: [
		        	{
		                data: 'DT_RowIndex',
		                name: 'DT_RowIndex'
		            },
		            {
		            	data: 'atb_group_id',
		            	name: 'atb_group_id'
		            },
		            {
		                data: 'atb_name',
		                name: 'atb_name'
		            },		            
		            {
		                data: 'atb_fillable',
		                name: 'atb_fillable'
		            },
		            {
		                data: 'action',
		                name: 'action',
		                orderable: false,
		                searchable: false
		            }
		        ]
			});
		});
	</script>
@endsection

resources/views/admin/attribute/attribute-specification/update.blade.php
@extends('admin.layout.master-admin')
@section('content')
<div class="content-header">
	<div class="container-fluid">
		<div class="row mb-2">
			<div class="col-sm-6">
				<h1 class="m-0 text-dark">Attribute</h1>
			</div><!-- /.col -->
			<div class="col-sm-6">
				<ol class="breadcrumb float-sm-right">
					<li class="breadcrumb-item"><a href="#">Home</a></li>
					<li class="breadcrumb-item"><a href="#">Attribute</a></li>
					<li class="breadcrumb-item active">Edit</li>
				</ol>
			</div><!-- /.col -->
		</div><!-- /.row -->
	</div><!-- /.container-fluid -->
</div>
<!-- Main content -->
<section class="content">
	<!-- Default card -->	
	<div class="row">
		<div class="col-12">
			<div class="card card-primary">
				<div class="card-header">
					<h3 class="card-title">Update Attribute</h3>
				</div>   
				<div class="card-body">					
					<div class="row">
						<div class="col-3">
							<h4>Attribute Information</h4>
							<div class="nav flex-column nav-tabs fix-tab" id="vert-tabs-tab" role="tablist" aria-orientation="vertical">
								<a class="nav-link active" id="vert-tabs-general-tab" data-toggle="pill" href="#vert-tabs-general" role="tab" aria-controls="vert-tabs-general" aria-selected="true">General</a>
								<a class="nav-link" id="vert-tabs-value-tab" data-toggle="pill" href="#vert-tabs-value" role="tab" aria-controls="vert-tabs-value" aria-selected="false">Values</a>
							</div>
						</div>
						<div class="col-9">
							<div class="tab-content" id="vert-tabs-tabContent">
								<div class="tab-pane tab-fix text-left fade show active" id="vert-tabs-general" role="tabpanel" aria-labelledby="vert-tabs-general-tab">
									<form action="" method="POST" class="form-horizontal">
										@csrf
										<h4>General</h4>
										<div class="form-group">
											<div class="row">
												<label for="attribute-group" class="col-md-3">Attribute Group <span class="text-danger">*</span></label>
												<div class="col-md-6">
													<select class="form-control {{ $errors->first('txt_attributeGroup') ? 'is-invalid' : ''}}" name="txt_attributeGroup">
														<option disabled>--Select choose option--</option>
														@if(isset($categories))
															@foreach($categories as $cate)
																 <optgroup label="{{ $cate->c_name}}">
																 	@foreach($attributeGroup as $attr)
																 		@if($cate->att_category_id == $attr->att_category_id)
																 			<option value="{{$attr->id}}" {{$attr->id == $attribute->atb_group_id ? 'selected' : ''}}>
																 				{{$attr->att_name}}
																 			</option>
																 		@endif
																 	@endforeach
																 </optgroup>
															@endforeach
														@endif
													</select>
													@if ($errors->first('txt_attributeGroup'))
						            					<p class="text-danger">{{ $errors->first('txt_attributeGroup') }}</p>
						            				@endif
												</div>
											</div>
										</div>
										<div class="form-group">
											<div class="row">
												<label for="attribute-name" class="col-md-3">Name <span class="text-danger">*</span></label>
												<div class="col-md-6">
													<input type="text" name="txt_attributeName" class="form-control {{ $errors->first('txt_attributeName') ? 'is-invalid' : '' }}" placeholder="Name" autocomplete="off" value="{{$attribute->atb_name}}">
													@if ($errors->first('txt_attributeName'))
						            					<p class="text-danger">{{ $errors->first('txt_attributeName') }}</p>
						            				@endif
												</div>
											</div>
										</div>
										<div class="form-group">
											<div class="row">
												<label for="attribute-filter" class="col-md-3">Filterable</label>
												<div class="col-md-6">
													<div class="custom-control custom-checkbox">
							                          <input class="custom-control-input" type="checkbox" id="customCheckbox1" value="option1">
							                          <label for="customCheckbox1" class="custom-control-label">Use this attribute for filtering products</label>
							                        </div>
												</div>
											</div>
										</div>
										<div class="row">
											<div class="col-md-6 offset-md-3">
												<button type="submit" class="btn btn-success">Save <i class="fa fa-save"></i></button>
											</div>
										</div>
									</form>
								</div>
								<div class="tab-pane tab-fix fade" id="vert-tabs-value" role="tabpanel" aria-labelledby="vert-tabs-value-tab">
									<form action="{{ route('admin.attributeValue.store', $attribute->id) }}" method="POST" class="form-horizontal">
										@csrf
										<h4>Values</h4>
										<div class="table-responsive">
											<table class="table-attribute border">
												<thead class="border-bottom">
													<tr>
														<th></th>
														<th>Value</th>
														<th></th>
													</tr>
												</thead>
												<tbody>
													@if(!count($attributeValue))
													<tr>
														<td class="drag-attribute"><i class="fas fa-bars"></i></td>
														<td class="px-2">
															<input type="hidden" name="txtAttribute[0][id]" value="">
															<input type="text" autocomplete="off" required class="form-control" name="txtAttribute[0][value]">
														</td>
														<td class="trash-attribute"><a href="javascript:void(0)" class="btn btn-default" title="Delete Value"><i class="fa fa-trash"></i></a></td>
													</tr>
													@else
													@foreach($attributeValue as $key => $val)
														<tr>
															<td class="drag-attribute"><i class="fas fa-bars"></i></td>
															<td class="px-2">
																<input type="hidden" name="txtAttribute[{{$key}}][id]" value="{{$val->id}}">
																<input type="text" autocomplete="off" required class="form-control" name="txtAttribute[{{$key}}][value]" value="{{$val->atb_val_name}}">
															</td>
															<td class="trash-attribute"><a href="javascript:void(0)" class="btn btn-default btn-remove" title="Delete Value"><i class="fa fa-trash"></i></a></td>
														</tr>
													@endforeach
													@endif
												</tbody>
											</table>
										</div>
										<div class="attribute-btn d-flex flex-column align-items-start">
											<a href="javascript:void(0)" class="btn btn-default my-3 btn-value">Add New Value</a>
											<button class="btn btn-primary">Save</button>
										</div>
									</form> 
								</div>
							</div>
						</div>
					</div>
				</div>         
			</div>
			<!-- /.box -->
		</div>
	</div>
</section><!-- /.content -->

@endsection